In [1]:
def exceptionHandler(num):
    try:
        r = num/0
        print("Result : "+ str(r))
    except:
        print("Number won't divisable by 0")
    
exceptionHandler(5)

Number won't divisable by 0


In [2]:
subjects=["Americans","Indians"] 
verbs=["play","watch"] 
objects=["Baseball","Cricket"] 
for i in subjects:
    for j in verbs:
        for k in objects:
            print(i + " " + j + " " + k)

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


In [3]:
import numpy as np

def gen_geometric_matrix(vector, n, booleanArg=False):
    
    if not booleanArg:
        matrix = np.asmatrix([x**(n-1-i) for x in vector for i in range(n)]).reshape(vector.size,n)
    elif booleanArg:
        matrix = np.asmatrix([x**i for x in vector for i in range(n)]).reshape(vector.size,n)
    return matrix

vector = np.array([1,2,3,4,5])
n = 3
matrix1 = gen_geometric_matrix(vector,n,False)
matrix2 = gen_geometric_matrix(vector,n,True)
print(matrix1)
print(matrix2)

[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]]
[[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]]
